services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    working_dir: /app

  peepa:
    build:
      context: ../peepa
      dockerfile: Dockerfile.dev
    volumes:
      - ../peepa:/app
    env_file:
      - .env.peepa

  proxy:
    build:
      context: ../proxy
      dockerfile: Dockerfile.dev
    ports:
      - "8888:80"
